import Head from 'next/head';
import Layout from '../components/Layout/index';
import Script from 'next/script';
const Home = () => {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Layout>
            <h3>Hello</h3>
         </Layout>
         <Script
            src="https://cdn.lordicon.com/xdjxvujz.js"
            strategy="lazyOnload"
            onLoad={() => console.log('script on load')}
         />
      </div>
   );
};

export default Home;
